# Generated by Django 4.2.3 on 2023-09-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nO_of_likes',
            new_name='no_of_likes',
        ),
    ]
